//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Negocios2017Entities : DbContext
    {
        public Negocios2017Entities()
            : base("name=Negocios2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_clientes> tb_clientes { get; set; }
        public virtual DbSet<tb_paises> tb_paises { get; set; }
    
        public virtual int USP_ACTUALIZARCLIENTEF(string id, string nom, string dir, string idp, string tel)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var idpParameter = idp != null ?
                new ObjectParameter("idp", idp) :
                new ObjectParameter("idp", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_ACTUALIZARCLIENTEF", idParameter, nomParameter, dirParameter, idpParameter, telParameter);
        }
    
        public virtual int USP_AGREGARCLIENTEF(string id, string nom, string dir, string idp, string tel)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var idpParameter = idp != null ?
                new ObjectParameter("idp", idp) :
                new ObjectParameter("idp", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_AGREGARCLIENTEF", idParameter, nomParameter, dirParameter, idpParameter, telParameter);
        }
    
        public virtual int USP_ELIMINARF(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_ELIMINARF", idParameter);
        }
    
        public virtual ObjectResult<USP_LISTACLIENTEF_Result> USP_LISTACLIENTEF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LISTACLIENTEF_Result>("USP_LISTACLIENTEF");
        }
    
        public virtual ObjectResult<USP_LISTAPAISESF_Result> USP_LISTAPAISESF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LISTAPAISESF_Result>("USP_LISTAPAISESF");
        }
    }
}
